### ISSUE TITLE
No output in the original format when the switch or end contains a blank symbol

### ISSUE THREAD

**Issue by wll8** [vitaly-t/decomment#24] opened 2021-09-14 12:06 UTC
## No output in the original format when the switch or end contains a blank symbol

For example, when there are multiple spaces.
## environment
- decomment@0.9.4

## How to reproduce
The result of this place should be `true`

``` js
const decomment = require('decomment')
const raw = `
    html {
      margin: 0;
      padding: 0;
    }
  
`
const res = decomment.text(raw)
console.log(`res`, res === raw) // false => The result of this place should be `true`
```

**Comment by vitaly-t** [comment] 2021-10-31 03:41
Most likely your editor issue, when it compiles line breaks differently from when it passes it in as a string. Make sure you do not extraneous white spaces there, which may be truncated at the end.

**Comment by wll8** [comment] 2021-10-31 03:52
So the above use case cannot be reproduced on your computer, right?
Or do you think this is not a problem to be solved?

**Comment by vitaly-t** [comment] 2021-10-31 03:54
I can reproduce it by tweaking end symbols to contain extra spaces on lines.

Anyway, I wouldn't expect identical text just because it doesn't contain comment blocks.

**Comment by vitaly-t** [comment] 2022-11-17 03:03
Closing, for being old, and no follow-up.

**Closed by vitaly-t** 2022-11-17 03:03 UTC
