### ISSUE TITLE
fails to minify

### ISSUE THREAD

**Issue by bingjianguo** [vitaly-t/decomment#16] opened 2018-03-13 05:17 UTC
The package be published pre-compiled. Can it be compiled to ES5 modue?

And, I can provide a pr for it.

**Comment by vitaly-t** [comment] 2018-03-13 09:59
This module removes comments, it doesn't do code minification. So what are you talking about?

**Comment by vitaly-t** [comment] 2018-03-15 10:37
Closing, because it is not clear what the issue is, and no further details provided.

**Closed by vitaly-t** 2018-03-15 10:37 UTC

**Comment by bingjianguo** [comment] 2018-03-21 10:02
I used the decomment as the depedencies.
As the es6 grammar is used in the source code, it will cause error during modules compression for webpack 1.
